[package]
name = "rust-esp32-std-hello"
version = "0.15.1"
authors = ["ivmarkov"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "A demo binary crate for the ESP32 and ESP-IDF, which connects to WiFi, drives a small HTTP server and draws on a LED screen"
repository = "https://github.com/ivmarkov/rust-esp32-std-hello"
license = "MIT"
readme = "README.md"

# No xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true
opt-level = "z"

[profile.dev]
opt-level = "s"

[patch.crates-io]
# If you plan on using a riscv32 MCU like ESP32C3:
#   Always include this patch in your workspace / final binary crate as it is patching libc
#   to support the riscv32 architecture with newlib. A similar patch for the xtensa architecture
#   (ESP32, ESP32S2, ESP32S3) is already in libc since libc 0.2.76
# NOTE: Since 2021-08-12, you DON'T these from below, when using stock Rust 1.56!
libc = { git = "https://github.com/ivmarkov/libc.git" } # For The 1.54 compiler fork
#libc = { git = "https://github.com/ivmarkov/libc.git", branch = "version_0.2.98" } # This is for the compiler forks older than 1.54

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
url = "2"
esp-idf-sys = "0.17"
embedded-svc = "0.8"
esp-idf-svc = { version = "0.17.1", features = ["binstart"] }
esp-idf-hal = "0.17"
embedded-hal = "0.2"
embedded-graphics = "0.7"
display-interface = "0.4"
display-interface-spi = "0.4"
st7789 = "0.6"
ili9341 = { version = "0.5", git = "https://github.com/ivmarkov/ili9341-rs" }
ssd1306 = "0.7"

#backtrace = { version = "0.3.56", path = "../backtrace-rs" }
#backtrace = { version = "0.3.56", git = "https://github.com/ivmarkov/backtrace-rs.git", branch = "esp-idf" }
#getrandom = { git = "https://github.com/ivmarkov/getrandom.git", branch = "0.1" }

[build-dependencies]
cargo-pio = "0.20.3"
anyhow = "1"

# Future; might be possible once https://github.com/rust-lang/cargo/issues/9096 hits Cargo nightly:
# rust-esp32-ulp-hello = { path = "../rust-esp32-ulp-hello", artifact = "bin" }
