[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2 or ESP32-C3)
target = "xtensa-esp32-espidf"
#target = "xtensa-esp32s2-espidf"
#target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"

[patch.crates-io]
# This patch is a temporary workaround necessary until Rust 1.55 is out
# You DON'T need it with stock nightly Rust 1.56 (but stock nightly only supports the ESP32-C3 chip)
libc = { git = "https://github.com/ivmarkov/libc.git" }

[unstable]
configurable-env = true # No longer necessary since 1.56, as it was stabilized: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/features.rs#L698
extra-link-arg = true   # No longer necessary since 1.56, as it was stabilized: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/features.rs#L695
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
patch-in-config = true

[env]
ESP_IDF_SYS_GLOB_BASE = { value = ".", relative = true }

# These two configurations will pick up your custom "sdkconfig" (for release builds) / "sdkconfig.debug" (for debug bulds) that you might put in the root of the project
# The easiest way to generate these configurations is by running "cargo pio espidf menuconfig"
# NOTE: You need latest Cargo nightly for that, and the rustc toolchain prebuilt by Espressif currently comes with an older version of Cargo that you have to remove
# The older Cargo version spits out `warning:Unknown argument "configurable-env = true"`
ESP_IDF_SYS_GLOB_0 = { value = "/sdkconfig.release" }
ESP_IDF_SYS_GLOB_1 = { value = "/sdkconfig.debug" }
ESP_IDF_SYS_GLOB_2 = { value = "/sdkconfig.defaults" }

# Uncomment both lines below if you plan to place and use a custom partition table, "partitions.csv" at the root of this project
# Note that the espflash utility is always flashing with its own partition table, which contains a single factory app of 3M max,
# so you should use the esptool.py utility to flash the custom partition table and the app
# Also see above regarding the Cargo version
#ESP_IDF_SYS_GLOB_3 = { value = "/partitions.csv" }
#ESP_IDF_SYS_PIO_CONF_0 = { value = "board_build.partitions = partitions.csv" }
